services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  server:
    build: ./server
    ports:
      - 5000:5000
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - 3000:4173
    depends_on:
      - server
      - python_script

  python_script:
    build: ./scripts/python
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=5000
    depends_on:
      - server
